---

- name: "Start {{service_name}}.service"
  systemd:
    name: "{{service_name}}.service"
    state: started

- block:
  - name: "Stop {{service_name}}.service"
    systemd:
      name: "{{service_name}}.service"
      state: stopped

  - name: "Restart {{service_name}}.service"
    systemd:
      name: "{{service_name}}.service"
      state: restarted

  - name: "Reload {{service_name}}.service"
    systemd:
      name: "{{service_name}}.service"
      state: reloaded
  when: service.service_config.Type is undefined or service.service_config.Type != 'oneshot'
