---

- name: "start systemd managed service"
  systemd:
    name: "{{service_name}}.service"
    state: started
  listen: "start application"
  when: service is defined

- block:
  - name: "stop systemd managed service"
    systemd:
      name: "{{service_name}}.service"
      state: stopped
    listen: "stop application"

  - name: "restart systemd managed service"
    systemd:
      name: "{{service_name}}.service"
      state: restarted
    listen: "restart application"

  - name: "reload systemd managed service"
    systemd:
      name: "{{service_name}}.service"
      state: reloaded
    listen: "reload application"
  when: service is defined and service.service_config.Type is undefined or service.service_config.Type != 'oneshot'
